version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
      docker_layer_caching: true
   steps:
     - checkout
     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
     # build the application image
     - run: docker build -t toune/nextcloud-facial-recognition:latest .
     - run: docker push toune/nextcloud-facial-recognition:latest
